Fix count tokens to include model params
google-gemini/generative-ai-js pull request #209
Opened 2024-07-12 22:41 UTC by hsubox76

Count tokens request should include any params set on the model parent class, including systemInstruction, tools, cachedContent.

Updated samples to use this.

generationConfig, toolConfig, and safetySettings don't seem like they would affect tokenCount but might as well pass them through, as they are part of a complete GenerateContentRequest and may affect tokenCount in the future.

2024-07-13 17:41 UTC, DellaBitta requested changes

2024-07-13 17:41 UTC, DellaBitta commented on packages/main/src/requests/request-helpers.ts
> +  // };
Should this be removed?

2024-07-13 17:41 UTC, DellaBitta commented on packages/main/src/requests/request-helpers.test.ts
> +      // expect(result.generateContentRequest.contents).to.equal("gemini-1.5-flash");
Remove these?

2024-07-15 17:03 UTC, hsubox76 commented on packages/main/src/requests/request-helpers.ts
> +  // };
Yep, thanks!

2024-07-15 17:03 UTC, hsubox76 commented on packages/main/src/requests/request-helpers.test.ts
> +      // expect(result.generateContentRequest.contents).to.equal("gemini-1.5-flash");
Done.

2024-07-15 17:34 UTC, DellaBitta approved these changes

2024-07-15 17:58 UTC, merged